HairCut/Models/Testimonial.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairCut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int Id { get; set; }
        public string Heading { get; set; }
        public string Profession { get; set; }
        public string Comment { get; set; }
    }
}

HairCut/Controllers/TestimonialsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HairCut.Models;

namespace HairCut.Controllers
{
    [Authorize]
    public class TestimonialsController : Controller
    {
        private HaircutEntities db = new HaircutEntities();
        public ActionResult Index()
        {
            return View(db.Testimonials.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Testimonial testimonial)
        {
            if (ModelState.IsValid)
            {
                db.Testimonials.Add(testimonial);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(testimonial);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Testimonial testimonial = db.Testimonials.Find(id);
            if (testimonial == null)
            {
                return HttpNotFound();
            }
            return View(testimonial);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Testimonial testimonial)
        {
            if (ModelState.IsValid)
            {
                db.Entry(testimonial).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(testimonial);
        }
        public ActionResult Delete(int id)
        {
            Testimonial testimonial = db.Testimonials.Find(id);
            db.Testimonials.Remove(testimonial);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HairCut/Views/Testimonials/Create.cshtml
@model HairCut.Models.Testimonial

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="main_content_iner ">
    <div class="container-fluid p-0 sm_padding_15px">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <h3 class="m-0">Testimonials</h3>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        @using (Html.BeginForm("Create", "Testimonials", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Name</label>
                                        @Html.EditorFor(model => model.Heading, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Heading" } })
                                        @Html.ValidationMessageFor(model => model.Heading, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Profession</label>
                                        @Html.EditorFor(model => model.Profession, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Profession" } })
                                        @Html.ValidationMessageFor(model => model.Profession, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Comment</label>
                                        @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Comment" } })
                                        @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Add</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HairCut/Views/Testimonials/Edit.cshtml
@model HairCut.Models.Testimonial

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main_content_iner ">
    <div class="container-fluid p-0 sm_padding_15px">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <h3 class="m-0">Testimonials</h3>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        @using (Html.BeginForm("Create", "Testimonials", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(x => x.Id)
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Name</label>
                                        @Html.EditorFor(model => model.Heading, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Heading" } })
                                        @Html.ValidationMessageFor(model => model.Heading, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Profession</label>
                                        @Html.EditorFor(model => model.Profession, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Profession" } })
                                        @Html.ValidationMessageFor(model => model.Profession, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Comment</label>
                                        @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Comment" } })
                                        @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success">Update</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HairCut/Views/Testimonials/Index.cshtml
@model IEnumerable<HairCut.Models.Testimonial>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main_content_iner ">
    <div class="container-fluid p-0">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <a href="/Testimonials/Create" class="btn btn-success btn-sm">Add New Testimonial</a>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        <div class="QA_section">
                            <div class="QA_table mb_30">

                                <table class="table lms_table_active3 ">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Name</th>
                                            <th scope="col">Profession</th>
                                            <th scope="col" style="width:56%;">Comment</th>
                                            <th scope="col">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{ int i = 1;}
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <th scope="row"> @i </th>
                                                <td>@item.Heading</td>
                                                <td>@item.Profession</td>
                                                <td>@item.Comment</td>
                                                <td>
                                                    @Html.ActionLink("Edit", "Edit", "Testimonials", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" }) |
                                                    @Html.ActionLink("Delete", "Delete", "Testimonials", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                                                </td>
                                            </tr>
                                            i++;
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>