HairCut/Models/Service.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairCut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service : Image
    {
        public int Id { get; set; }
        public string Heading { get; set; }
        public string Text { get; set; }
        public string Price { get; set; }
        public string ImgPath { get; set; }
    }
}

HairCut/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HairCut.Models;

namespace HairCut.Controllers
{
    [Authorize]
    public class ServicesController : Controller
    {
        private HaircutEntities db = new HaircutEntities();
        // GET: Services
        public ActionResult Index()
        {
            var List = db.Services.ToList();
            //ViewBag.List = List;
            return View(List);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Service service)
        {
            if (ModelState.IsValid)
            {
                var filename = Path.GetFileNameWithoutExtension(service.UserImagePath.FileName);
                var extension = Path.GetExtension(service.UserImagePath.FileName);
                filename = filename + DateTime.Now.ToString("yymmssff") + extension;
                service.ImgPath = "~/Content/uploaded/" + filename;
                filename = Path.Combine(Server.MapPath("~/Content/uploaded/"), filename);
                service.UserImagePath.SaveAs(filename);

                db.Services.Add(service);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(service);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Service service)
        {
            if (ModelState.IsValid)
            {
                var filename = Path.GetFileNameWithoutExtension(service.UserImagePath.FileName);
                var extension = Path.GetExtension(service.UserImagePath.FileName);
                filename = filename + DateTime.Now.ToString("yymmssff") + extension;
                service.ImgPath = "~/Content/uploaded/" + filename;
                filename = Path.Combine(Server.MapPath("~/Content/uploaded/"), filename);
                service.UserImagePath.SaveAs(filename);

                db.Entry(service).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(service);
        }
        public ActionResult Delete(int id)
        {
            Service service = db.Services.Find(id);
            db.Services.Remove(service);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HairCut/Views/Services/Create.cshtml
@model HairCut.Models.Service

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main_content_iner ">
    <div class="container-fluid p-0 sm_padding_15px">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <h3 class="m-0">Services</h3>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        @using (Html.BeginForm("Create", "Services", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Heading</label>
                                        @Html.EditorFor(model => model.Heading, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Heading" } })
                                        @Html.ValidationMessageFor(model => model.Heading, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Text</label>
                                        @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Text" } })
                                        @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Price</label>
                                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Price" } })
                                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Image</label>
                                        <input type="file" class="form-control" name="UserImagePath" />
                                        @Html.ValidationMessageFor(model => model.ImgPath, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Add</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HairCut/Views/Services/Delete.cshtml
@model HairCut.Models.Service

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Service</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Heading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Heading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImgPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImgPath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HairCut/Views/Services/Edit.cshtml
@model HairCut.Models.Service

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main_content_iner ">
    <div class="container-fluid p-0 sm_padding_15px">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <h3 class="m-0">Services</h3>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        @using (Html.BeginForm("Edit", "Services", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(x => x.Id)
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Heading</label>
                                        @Html.EditorFor(model => model.Heading, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Heading" } })
                                        @Html.ValidationMessageFor(model => model.Heading, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Address</label>
                                        @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Address" } })
                                        @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Phone No</label>
                                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Phone No" } })
                                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Image</label>
                                        <input type="file" class="form-control" name="UserImagePath" />
                                        @Html.ValidationMessageFor(model => model.ImgPath, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success">Update</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HairCut/Views/Services/Index.cshtml
@model IEnumerable<HairCut.Models.Service>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="main_content_iner ">
    <div class="container-fluid p-0">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <a href="/Services/Create" class="btn btn-success btn-sm">Add New Service</a>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        <div class="QA_section">
                            <div class="QA_table mb_30">

                                <table class="table lms_table_active3 ">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Heading</th>
                                            <th scope="col">Text</th>
                                            <th scope="col">Image</th>
                                            <th scope="col">Price</th>
                                            <th scope="col">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{ int i = 1;}
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <th scope="row"> @i </th>
                                                <td>@item.Heading</td>
                                                <td>@item.Text</td>
                                                <td><img src="@Url.Content(item.ImgPath)" style="width: 80px; height:50px;" /> </td>
                                                <td>@item.Price</td>
                                                <td>
                                                    @Html.ActionLink("Edit", "Edit", "Services", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" }) |
                                                    @Html.ActionLink("Delete", "Delete", "Services", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                                                </td>
                                            </tr>
                                            i++;
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>