HairCut/Models/Barbar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairCut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barbar : Image
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string ImagePath { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
    }
}

HairCut/Controllers/BarbarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HairCut.Models;

namespace HairCut.Controllers
{
    [Authorize]
    public class BarbarsController : Controller
    {
        private HaircutEntities db = new HaircutEntities();
        public ActionResult Index()
        {
            return View(db.Barbars.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Barbar barbar)
        {
            if (ModelState.IsValid)
            {
                var filename = Path.GetFileNameWithoutExtension(barbar.UserImagePath.FileName);
                var extension = Path.GetExtension(barbar.UserImagePath.FileName);
                filename = filename + DateTime.Now.ToString("yymmssff") + extension;
                barbar.ImagePath = "~/Content/uploaded/" + filename;
                filename = Path.Combine(Server.MapPath("~/Content/uploaded/"), filename);
                barbar.UserImagePath.SaveAs(filename);

                db.Barbars.Add(barbar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(barbar);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Barbar barbar = db.Barbars.Find(id);
            if (barbar == null)
            {
                return HttpNotFound();
            }
            return View(barbar);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Barbar barbar)
        {
            if (ModelState.IsValid)
            {
                var filename = Path.GetFileNameWithoutExtension(barbar.UserImagePath.FileName);
                var extension = Path.GetExtension(barbar.UserImagePath.FileName);
                filename = filename + DateTime.Now.ToString("yymmssff") + extension;
                barbar.ImagePath = "~/Content/uploaded/" + filename;
                filename = Path.Combine(Server.MapPath("~/Content/uploaded/"), filename);
                barbar.UserImagePath.SaveAs(filename);

                db.Entry(barbar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(barbar);
        }
        public ActionResult Delete(int id)
        {
            Barbar barbar = db.Barbars.Find(id);
            db.Barbars.Remove(barbar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HairCut/Views/Barbars/Create.cshtml
@model HairCut.Models.Barbar

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main_content_iner ">
    <div class="container-fluid p-0 sm_padding_15px">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <h3 class="m-0">Barbars</h3>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        @using (Html.BeginForm("Create", "Barbars", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="mb-3">
                                    <label class="form-label">Name</label>
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="mb-3">
                                    <label class="form-label">Designation</label>
                                    @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Designation" } })
                                    @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="mb-3">
                                    <label class="form-label">Facebook</label>
                                    @Html.EditorFor(model => model.Facebook, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Facebook" } })
                                    @Html.ValidationMessageFor(model => model.Facebook, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="mb-3">
                                    <label class="form-label">Twitter</label>
                                    @Html.EditorFor(model => model.Twitter, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Twitter" } })
                                    @Html.ValidationMessageFor(model => model.Twitter, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="mb-3">
                                    <label class="form-label">Instagram</label>
                                    @Html.EditorFor(model => model.Instagram, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Instagram" } })
                                    @Html.ValidationMessageFor(model => model.Instagram, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="mb-3">
                                    <label class="form-label">Image</label>
                                    <input type="file" class="form-control" name="UserImagePath" />
                                    @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                            <button type="submit" class="btn btn-primary">Add</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HairCut/Views/Barbars/Edit.cshtml
@model HairCut.Models.Barbar

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main_content_iner ">
    <div class="container-fluid p-0 sm_padding_15px">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <h3 class="m-0">Barbars</h3>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        @using (Html.BeginForm("Create", "Barbars", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(x => x.Id)
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Name</label>
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Designation</label>
                                        @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Designation" } })
                                        @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Facebook</label>
                                        @Html.EditorFor(model => model.Facebook, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Facebook" } })
                                        @Html.ValidationMessageFor(model => model.Facebook, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Facebook</label>
                                        @Html.EditorFor(model => model.Twitter, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Twitter" } })
                                        @Html.ValidationMessageFor(model => model.Twitter, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Instagram</label>
                                        @Html.EditorFor(model => model.Instagram, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Instagram" } })
                                        @Html.ValidationMessageFor(model => model.Instagram, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Image</label>
                                        <input type="file" class="form-control" name="UserImagePath" />
                                        @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success">Update</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HairCut/Views/Barbars/Index.cshtml
@model IEnumerable<HairCut.Models.Barbar>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="main_content_iner ">
    <div class="container-fluid p-0">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <a href="/Barbars/Create" class="btn btn-success btn-sm">Add New Barbar</a>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        <div class="QA_section">
                            <div class="QA_table mb_30">

                                <table class="table lms_table_active3 ">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Name</th>
                                            <th scope="col">Designation</th>
                                            <th scope="col">Image</th>
                                            <th scope="col">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{ int i = 1;}
                                        @foreach (var item in Model)
                                        {
                                        <tr>
                                            <th scope="row"> @i </th>
                                            <td>@item.Name</td>
                                            <td>@item.Designation</td>
                                            <td><img src="@Url.Content(item.ImagePath)" style="width: 80px; height:50px;" /> </td>
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", "Barbars", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" }) |
                                                @Html.ActionLink("Delete", "Delete", "Barbars", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                                            </td>
                                        </tr>
                                            i++;
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>