HairCut/Models/Working_Hours.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairCut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Working_Hours
    {
        public int Id { get; set; }
        public string Days { get; set; }
        public string Timing { get; set; }
    }
}

HairCut/Controllers/Working_HoursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HairCut.Models;

namespace HairCut.Controllers
{
    [Authorize]
    public class Working_HoursController : Controller
    {
        private HaircutEntities db = new HaircutEntities();
        public ActionResult Index()
        {
            return View(db.Working_Hours.ToList());
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Working_Hours working_Hours = db.Working_Hours.Find(id);
            if (working_Hours == null)
            {
                return HttpNotFound();
            }
            return View(working_Hours);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Working_Hours working_Hours)
        {
            if (ModelState.IsValid)
            {
                db.Working_Hours.Add(working_Hours);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(working_Hours);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Working_Hours working_Hours = db.Working_Hours.Find(id);
            if (working_Hours == null)
            {
                return HttpNotFound();
            }
            return View(working_Hours);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Working_Hours working_Hours)
        {
            if (ModelState.IsValid)
            {
                db.Entry(working_Hours).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(working_Hours);
        }
        public ActionResult Delete(int id)
        {
            Working_Hours working_Hours = db.Working_Hours.Find(id);
            db.Working_Hours.Remove(working_Hours);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HairCut/Views/Working_Hours/Create.cshtml
@model HairCut.Models.Working_Hours

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main_content_iner ">
    <div class="container-fluid p-0 sm_padding_15px">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <h3 class="m-0">Working Hours</h3>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        @using (Html.BeginForm("Create", "Working_Hours", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Days</label>
                                        @Html.EditorFor(model => model.Days, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Days" } })
                                        @Html.ValidationMessageFor(model => model.Days, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Timing</label>
                                        @Html.EditorFor(model => model.Timing, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Timing" } })
                                        @Html.ValidationMessageFor(model => model.Timing, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Add</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HairCut/Views/Working_Hours/Edit.cshtml
@model HairCut.Models.Working_Hours

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main_content_iner ">
    <div class="container-fluid p-0 sm_padding_15px">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <h3 class="m-0">Working Hours</h3>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        @using (Html.BeginForm("Edit", "Working_Hours", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(x => x.Id)
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Days</label>
                                        @Html.EditorFor(model => model.Days, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Days" } })
                                        @Html.ValidationMessageFor(model => model.Days, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Timing</label>
                                        @Html.EditorFor(model => model.Timing, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Timing" } })
                                        @Html.ValidationMessageFor(model => model.Timing, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Add</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HairCut/Views/Working_Hours/Index.cshtml
@model IEnumerable<HairCut.Models.Working_Hours>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main_content_iner ">
    <div class="container-fluid p-0">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <a href="/Working_Hours/Create" class="btn btn-success btn-sm">Add New Working Hour</a>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        <div class="QA_section">
                            <div class="QA_table mb_30">

                                <table class="table lms_table_active3 ">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Days</th>
                                            <th scope="col">Timing</th>
                                            <th scope="col">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{int i = 1;}
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <th scope="row"> @i </th>
                                                <td>@item.Days</td>
                                                <td>@item.Timing</td>
                                                <td>
                                                    @Html.ActionLink("Edit", "Edit", "Working_Hours", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" }) |
                                                    @Html.ActionLink("Delete", "Delete", "Working_Hours", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                                                </td>
                                            </tr>
                                            i++;
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>